### ISSUE TITLE
distortion query

### ISSUE THREAD

**Issue by themkar** [oliviaguest/random-dots#2]
Am I getting this right @oliviaguest ?

[Here](https://github.com/oliviaguest/random-dots/blob/master/randomdots.py#L275-L277) distortion is a var used for generating the binary vectors from prototypes. These lines of code imply that when you define a list of items per category, distortion is equal to 1, [because of this](https://github.com/oliviaguest/random-dots/blob/master/randomdots.py#L69-L72). 
You cannot set this variable externally when you have a list of items per category.

[Here](https://github.com/oliviaguest/random-dots/blob/master/randomdots.py#L152) is another distortion related to the blurring during compression, which you can set externally.

Thanks!

**Comment by oliviaguest** [comment]
Yes, 100% correct.

**Comment by oliviaguest** [comment]
Variables with `self.` prefix are attributes that exist as long as the object exists. While the first `distortion` you mention is only in scope for the function it is in.
